### ISSUE TITLE
--ERROR: MAX_N_PID exceded -- Recompile changing the value of MAX_N_PID

### ISSUE THREAD

**Issue by WellJoea** [cbcrg/tcoffee#23]
t_coffee -version
PROGRAM: T-COFFEE Version_13.41.0.28bdc39 (2019-11-30 10:21:53 - Revision 5d5a1c1 - Build 465)

--ERROR: MAX_N_PID exceded -- Recompile changing the value of MAX_N_PID (current: 260000 Requested: 280441)

**Comment by matrs** [comment]
See here:
https://groups.google.com/forum/#!topic/tcoffee/sO8Kd5NjA5A

**Comment by cnotred** [comment]
This issue is now closed. Tghe max number of PID can be changed via the environement
