### ISSUE TITLE
PSICoffee - WARNING: [ncbiblast_lwp.pl] failed to produce xml output

### ISSUE THREAD

**Issue by AlbanMariette** [cbcrg/tcoffee#36]
Hello,
I am currently using t-coffee to perform multiple sequence alignment of proteins to study evolution of transmembrane protein. Since recently I cannot use t-coffee anymore because of an issue with BLAST and it does not seem to be due to t-coffee because I face this issue either with the 13.41.0 or the last beta version 13.44.4.6104691.

I get the following output:
WARNING: [ncbiblast_lwp.pl] [t_coffee -other_pg ncbiblast_lwp.pl --email myemail -D uniref50 -p blastp --outfile outfile --align 5 --stype protein seqfile>/dev/null 2>file.95815.2458162175.32833] failed to produce xml output -- will ne tried again [1]

And this message keep appearing with the numbers incrementing, suggesting that the BLAST does not work correctly. I did some test and it is not sequence dependent. Apparently my email is accepted because I don't get the error "BLAST_FAILURE::Invalid_or_rejected_email"

Do you have any idea where this warning could come from, and why it fails to produce xml output ?

Thank you for your help,
if you would need more information please let me know.

Alban

**Comment by athbaltzis** [comment]
Hi Alban,
Thank you for your bug report. You can try the latest commit in which the issue with blast should be fixed.

Please let me know if you face any other issue.

Athanasios

**Comment by AlbanMariette** [comment]
Hi athbaltzis,
Thanks for your reply we are currently testing the last version. It however ran into an unresolved lock during the alignment process, the administrator of the HPC are currently looking at it.
Best,
Alban

**Comment by cnotred** [comment]
The unresolved lock is an issue that occasionally pops up and that we are investigating. It should only have an impact on temp files being left over. But if it results in other Pb on your side please let me know

Cheers 

Cedric 

###################################
Dr Cedric Notredame
Group Leader
Notredame's lab - Comparative Bioinformatics Group
Bioinformatics and Genomics Programme
Room 440.03

Centre de Regulació Genòmica (CRG)
Dr. Aiguader, 88
08003 Barcelona
Spain

Ph#     + 34 93 316 02 71
Fax#    + 34 93 316 00 99
Mobile# + 34 66 250 47 82

email   cedric.notredame@crg.eu
url     www.tcoffee.org
blog    cedricnotredame.blogspot.com
ORC-ID: 0000-0003-1461-0988
###################################
