### ISSUE TITLE
tag v11

### ISSUE THREAD

**Issue by dunn** [cbcrg/tcoffee#4]
Your download page http://www.tcoffee.org/Projects/tcoffee/ says there's a new release; could you tag it here for the benefit of package managers?  Thanks!

**Comment by pditommaso** [comment]
What do you mean exactly? The latest version is published at this path 
http://www.tcoffee.org/Packages/Stable/Latest/

**Comment by dunn** [comment]
[Homebrew](http://brew.sh) at least likes to compile things from source, so a versioned tarball or something would be great.

**Comment by pditommaso** [comment]
I see, you mean to tag the version in Github. It makes sense.
