### ISSUE TITLE
Pin new releases for conda

### ISSUE THREAD

**Issue by matthdsm** [cbcrg/tcoffee#54]
Hi,

Would you be able to pin new releases in github, so these can be picked up by the bioconda bot?
Thanks
Matthias

**Comment by tillea** [comment]
Same for Debian packaging.  If you set do `git tag <version_number>` the world gets informed about a new release and distributions can pick this up.  This is way more convenient than tcoffee download page which has the disadvantage that it is JavaScript based and thus can only very hardly parsed by automated tools.
Thanks a lot for maintaining tcoffee on Github in any case.

**Comment by amizeranschi** [comment]
+1 on this request. The latest bioconda package is 3 and a half years old now.

**Comment by JoseEspinosa** [comment]
I think this should be fixed now @matthdsm.Llet us know if this is working now for the bioconda bot or how to check it. I saw that the last release tag is from 7 days ago. It might be that it has some latency to get new tags, though.
Thanks!

**Comment by matthdsm** [comment]
TBH, I can't remember why I asked this 😓

**Comment by JoseEspinosa** [comment]
No worries, we did not fix it very fast 😓

**Comment by amizeranschi** [comment]
@matthdsm I think I remember the issue around tcoffee in bioconda was nicely explained here: https://github.com/bioconda/bioconda-recipes/issues/32576#issuecomment-1126832613

**Comment by JoseEspinosa** [comment]
Thanks @amizeranschi for the feedback 😄
