### ISSUE TITLE
Stable download link doesn't work

### ISSUE THREAD

**Issue by pegetive** [cbcrg/tcoffee#55]
Hi.
The stable link to download T-Coffee doesn't work: [https://tcoffee.org/Packages/Stable/Latest]
Could you please fix it? Much appreciated.

**Comment by JoseEspinosa** [comment]
We migrate the website to s3 and we move the stable packages to [this](http://tcoffee-packages.s3-website.eu-central-1.amazonaws.com/#Stable/Latest/). If you navigate through the website it will lead you there (https://tcoffee.org/Projects/tcoffee/index.html#DOWNLOAD). Sorry for the inconvenience.

**Comment by cnotred** [comment]
Thanks for pointing this out. THis was due to our AWS migration. This should now be fixed
