### ISSUE TITLE
T-Coffee installer tarball changed

### ISSUE THREAD

**Issue by smoors** [cbcrg/tcoffee#57]
i downloaded the following tarball at different times, getting hugely different sources
https://s3.eu-central-1.amazonaws.com/tcoffee-packages/Archives/T-COFFEE_installer_Version_13.45.61.3c310a9_linux_x64.tar.gz

is there a place where i can download the original tarball (from 2022-12-09)?

please don't update tarballs in-place, change the version instead (that's what versions are for)? this is essential for reproducible science.

2022-12-09:
```
sha256sum T-COFFEE_installer_Version_13.45.61.3c310a9_linux_x64.tar.gz
8bc60336f5c203d4a20cc8c9e0ba10c5f4275a11ccfd15a0dd26a03510314513  T-COFFEE_installer_Version_13.45.61.3c310a9_linux_x64.tar.gz
```
2023-05-19
```
sha256sum new_download/T-COFFEE_installer_Version_13.45.61.3c310a9_linux_x64.tar.gz                              
194b89107ac31467f8a0221bd621c652d6a485a1886a65ef5d567699876429d4  new_download/T-COFFEE_installer_Version_13.45.61.3c310a9_linux_x64.tar.gz
```

**Comment by cnotred** [comment]
Thanks a lot for pointing this issue. We recently updated the production and obviously messed up something. We are working on it right now.

**Comment by JoseEspinosa** [comment]
Hi @smoors, thanks for reporting. We detected a problem in our CI and we are working on fixing it. Would be great if you could send us the tarball corresponding to the *2022-12-09* file since it was overwritten and we have lost it. Thanks a lot!

**Comment by smoors** [comment]
@JoseEspinosa sure, here is a link:
https://vub-my.sharepoint.com/:u:/g/personal/samuel_moors_vub_be/ERDKR6QDJoBKs3grQMTHiJQBPV_o1k__ied_KXvaMczIMw?e=6fGEaC

**Comment by JoseEspinosa** [comment]
This problems should be now fixed by #58, where the `build` and `test` processes in CI are always triggered while `publish` and `push_image` are only run when a new tag is pushed.

**Comment by JoseEspinosa** [comment]
@smoors should be fixed now, thanks for your patience.

**Comment by smoors** [comment]
fixed, thanks
